### ISSUE TITLE
can you upload also your emacs.png

### ISSUE THREAD

**Issue by sroeschus** [masasam/dotfiles#1]
I like your emacs.png, that is stored in your dropbox account. Is it possible to also upload it?

**Comment by masasam** [comment]
Hi @sroeschus .
Thanks for your comment.
I uploaded it to github.
See https://github.com/masasam/dotfiles/blob/cdad0f0ed33fd9f113406d06beb34df947b8d4cd/.emacs.d/emacs.png

**Comment by masasam** [comment]
test
