### ISSUE TITLE
Security Data Issues - Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [masasam/dotfiles#10]
Hi ,

url : https://github.com/masasam/dotfiles/tree/86297632b6569ef42bb537e238a93a49d0b75044/.ssh

have commit that need to remove from the github history
attacker can see it and use it ...

encrypt your secrets !!!!

Our Bug Help you to be more Secure and protect your data ?
Buy me a coffee (or more likely a beer)
https://www.buymeacoffee.com/bugbounty
☕☕☕☕☕

**Comment by masasam** [comment]
Hi @shaybenb .
Thank you for comment.
Since my .ssh/* is encrypted with [git-crypt](https://github.com/AGWA/git-crypt) , no worries about being used by attackers.
