### ISSUE TITLE
Not really a bug or anything but about makefile

### ISSUE THREAD

**Issue by thepenguinthatwants** [masasam/dotfiles#2]
Hi!

You inspired me to try make instead of just using own install.sh script.

There is something that I dont understand. If its okay I wanted to ask where do you need the export with?

`export PATH := ${HOME}/.local/bin:${HOME}/.node_modules/bin:${HOME}/.cargo/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/bin/core_perl:${HOME}/bin`

You do create those directories, but why do u need to export them in makefile?

```
nodeinstall: ## Install node packages
           mkdir -p ${HOME}/.node_modules
           yarn global add babel-eslint
```

**Comment by masasam** [comment]
Hi @thepenguinthatwants .
Thank you for comment. It works without export as you say. But when running Makefile immediately after OS installation, .bashrc or .zshrc has not been read yet. If I create a Makefile that uses create-nuxt-app when installing at once with make allinstall, it will not work. In this case, since Makefile doesn't read .bashrc or .zshrc, PATH is unknown. I don't want to think about this, so I've wrote export in the Makefile.

**Comment by thepenguinthatwants** [comment]
Hi!

Thanks now I understood it more clearly. There is also one more thing that I am wondering.
In your dockerfile you have 

`ARG USERNAME=masa`

How did you know that archlinux had those ARG variables?  I cant seem to find those infos anywhere.

**Comment by masasam** [comment]
@thepenguinthatwants My archlinux user name is masa (masasam is for online name). Unless I mount a host directory (/home/masa/Dropbox) with docker when run `make test` using Makefile, `make test` doesn't work. (See Makefile line 641 `docker run -v /home/${USER}/Dropbox:${HOME}/Dropbox:cached --name makefiletest -d dotfiles`)
This is why I've wrote masa to ARG in Dockerfile.

**Comment by thepenguinthatwants** [comment]
Hi!

Sorry I wrote the question quite confusingly. I meant how did you know that ARG USERNAME exist? That you could use it to create a user? Quite curious about what other ARG's exists in archlinux/base image.

**Comment by masasam** [comment]
```
ARG USERNAME=masa
ARG PASSWORD=hogehoge
```
ARG is a variable that can be used in dockerfile.
See https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact.
