### ISSUE TITLE
Manifest not found when I tried to run this against docker?

### ISSUE THREAD

**Issue by thepenguinthatwants** [masasam/dotfiles#6]
Hi!

I am trying to test your makefile and also to understand how to test my own.

When I run command

`make test`
I got

Step 1/22 : FROM base/archlinux:latest
manifest for base/archlinux:latest not found: manifest unknown: manifest unknown

**Comment by thepenguinthatwants** [comment]
Removing the base/ and it works.
But it breaks on

  ja_JP.UTF-8...[error] cannot open locale definition file `ja_JP': No such file or directory
Deleting that part it breaks on

 Cloning into 'yay'...
==> ERROR: Running makepkg as root is not allowed as it can cause permanent,
catastrophic damage to your system.

Wondering if this test should work?

**Comment by masasam** [comment]
Hi @thepenguinthatwants .
Thank you for comment.
I've fixed this bug.
