### ISSUE TITLE
Make test having issues at the end Step 32/32

### ISSUE THREAD

**Issue by thepenguinthatwants** [masasam/dotfiles#7]
Hi!

Sorry for this talking about the same thing.

So I tried running make test again and it went further.

Was wondering that if it

`make test
`

is enough or should I also make some changes based on the instructions on your dockerfiles?

sh: line 0: cd: /home/ninja/todo/dotfiles_treenit/dotfiles: No such file or directory
make: *** No rule to make target 'install'.  Stop.
sh: line 0: cd: /home/ninja/todo/dotfiles_treenit/dotfiles: No such file or directory
make: *** No rule to make target 'init'.  Stop.
sh: line 0: cd: /home/ninja/todo/dotfiles_treenit/dotfiles: No such file or directory
make: *** No rule to make target 'neomutt'.  Stop.
sh: line 0: cd: /home/ninja/todo/dotfiles_treenit/dotfiles: No such file or directory
make: *** No rule to make target 'aur'.  Stop.
sh: line 0: cd: /home/ninja/todo/dotfiles_treenit/dotfiles: No such file or directory
make: *** No rule to make target 'pipinstall'.  Stop.
sh: line 0: cd: /home/ninja/todo/dotfiles_treenit/dotfiles: No such file or directory
make: *** No rule to make target 'goinstall'.  Stop.
sh: line 0: cd: /home/ninja/todo/dotfiles_treenit/dotfiles: No such file or directory
make: *** No rule to make target 'nodeinstall'.  Stop.
make: *** [Makefile:614: test] Error 2

**Comment by masasam** [comment]
Hi @thepenguinthatwants .

https://github.com/masasam/dotfiles/blob/master/Dockerfile#L15

What if you set the following in this location of Dockerfile?

     ARG REPOSITORY=/home/ninja/todo/dotfiles_treenit

**Comment by thepenguinthatwants** [comment]
Successfully built 0a4531f93432
Successfully tagged dotfiles:latest
docker: Error response from daemon: Conflict. The container name "/maketest" is already in use by container "9ec47c3122c11bc94fd063c21d9777594b3e7f4bb69575187f1584fba972deb6". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
sh: line 0: cd: /home/ninja/todo/dotfiles_treenit/dotfiles: No such file or directory`

still same lines.

Tried
 ARG REPOSITORY=/home/ninja/todo/dotfiles_treenit
and also
 ARG REPOSITORY=/home/ninja/todo/dotfiles_treenit/dotfiles/

removing 9ec47c3122c11 images also didnt help

**Comment by thepenguinthatwants** [comment]
I tried running it again but now it fails earlier and looks like this.

Step 25/33 : RUN LANG=C xdg-user-dirs-update --force && mkdir -p ${REPOSITORY}
 ---> Running in aab95f88c772
mkdir: cannot create directory ‘/home/ninja’: Permission denied
The command '/bin/sh -c LANG=C xdg-user-dirs-update --force &&  mkdir -p ${REPOSITORY}' returned a non-zero code: 1
docker: Error response from daemon: Conflict. The container name "/maketest" is already in use by container "7d1dfe56014295434526ae0ab39f767a551ea0a63ff0509cc064882a1e716a6f". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
sh: line 0: cd: /home/ninja/todo/Makedotstreenit/dotfiles: No such file or directory
make: *** No rule to make target 'install'.  Stop.
sh: line 0: cd: /home/ninja/todo/Makedotstreenit/dotfiles: No such file or directory
make: *** No rule to make target 'init'.  Stop.
sh: line 0: cd: /home/ninja/todo/Makedotstreenit/dotfiles: No such file or directory
make: *** No rule to make target 'neomutt'.  Stop.
sh: line 0: cd: /home/ninja/todo/Makedotstreenit/dotfiles: No such file or directory
make: *** No rule to make target 'aur'.  Stop.
sh: line 0: cd: /home/ninja/todo/Makedotstreenit/dotfiles: No such file or directory
make: *** No rule to make target 'pipinstall'.  Stop.
sh: line 0: cd: /home/ninja/todo/Makedotstreenit/dotfiles: No such file or directory
make: *** No rule to make target 'goinstall'.  Stop.
sh: line 0: cd: /home/ninja/todo/Makedotstreenit/dotfiles: No such file or directory
make: *** No rule to make target 'nodeinstall'.  Stop.
make: *** [Makefile:614: test] Error 2

**Comment by thepenguinthatwants** [comment]
Stopping and running 7d1dfe5601429 doesnt help.

So my argument looks like this now.
ARG REPOSITORY=/home/ninja/todo/Makedotstreenit/

**Comment by masasam** [comment]
See

mkdir: cannot create directory ‘/home/ninja’: Permission denied
The command '/bin/sh -c LANG=C xdg-user-dirs-update --force && mkdir -p ${REPOSITORY}' returned a non-zero code: 1
docker: Error response from daemon: Conflict. The container name "/maketest" is already in use by container "7d1dfe56014295434526ae0ab39f767a551ea0a63ff0509cc064882a1e716a6f". You have to remove (or rename) that container to be able to reuse that name.


docker container rm 7d1dfe56014295434526
ARG USERNAME=ninja

**Comment by thepenguinthatwants** [comment]
OOOH!! DAMN ur good!! thanks
